### ISSUE TITLE
Creare spazio RTD di base

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/iXMapsDoc#1]

**Comment by gbvitrano** [comment]
RDT di base preparata **[ixmapsdoc.readthedocs.io](https://ixmapsdoc.readthedocs.io/)**
lo stile del css può essere modificato in qualsiasi momento  lo adattiamo ai contenuti del manuale :-)
il layout è una replica del manuale **[HfcGIS](http://hfcqgis.opendatasicilia.it/it/latest/)**
